apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
  strategy:
    type: Recreate
  #type: RollingUpdate #Recreate
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: localhost:32000/mynginx:registry
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysqldb
        - name: NEW_RELIC_LICENSE_KEY
          value: 697a9b6f81b1c52b52284dac94e98fc4FFFFNRAL
        - name: NEW_RELIC_APP_NAME
          value: "wlm" 
          

---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
spec:
  type: NodePort
  selector:
    app: mynginx

  ports:
    - port: 80 #NODE_DOCKER_PORT
      targetPort: 80 #NODE_DOCKER_PORT
      nodePort: 32088 #NODE_LOCAL_PORT