apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  selector:
    matchLabels:
      app: haproxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: localhost:32000/nginx-haproxy-docker_haproxy:registry
        ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 88
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
        env:
        - name: xxx
          value: yyy
---

apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
    - name: "88"
      port: 88
      targetPort: 88
  selector:
    app: haproxy
