apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-one
data:
  index.html: |
    <html>
    <head><title>Level Up!</title></head>
    <body/>
    <h1>This is Deployment One.</h1>
    </body></html>
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-two
data:
  index.html: |
    <html>
    <head><title>Level Up!</title></head>
    <body/>
    <h1>This is Deployment Two.</h1>
    </body></html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
          - containerPort: 80
        volumeMounts:
        - name: config-1
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-1
        configMap:
          name: configmap-one

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
          - containerPort: 80
        volumeMounts:
        - name: config-2
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-2
        configMap:
          name: configmap-two

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: my-service
      port: 80
      targetPort: 80