apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-2
spec:
  selector:
    matchLabels:
      app: nginx-web-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-web-2
    spec:
      containers:
      - name: nginx-web-2
        image: localhost:32000/nginx-haproxy-docker_nginx_web_2:registry
        ports:
        - containerPort: 80
        env:
        - name: xxx
          value: yyy
---

apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nginx-web-2
  name: nginx-web-2
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: nginx-web-2
